# Generated by Django 6.0.3 on 2026-03-13 19:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title_cs', models.CharField(max_length=120)),
                ('title_en', models.CharField(max_length=120)),
                ('description_cs', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'title_en'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title_cs', models.CharField(max_length=120)),
                ('title_en', models.CharField(max_length=120)),
                ('subtitle_cs', models.CharField(blank=True, max_length=180)),
                ('subtitle_en', models.CharField(blank=True, max_length=180)),
                ('description_cs', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('atmosphere_cs', models.TextField(blank=True)),
                ('atmosphere_en', models.TextField(blank=True)),
                ('theme_key', models.CharField(blank=True, max_length=80)),
                ('ambient_key', models.CharField(blank=True, max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'title_en'],
            },
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name_cs', models.CharField(max_length=160)),
                ('name_en', models.CharField(max_length=160)),
                ('year_or_era_cs', models.CharField(blank=True, max_length=160)),
                ('year_or_era_en', models.CharField(blank=True, max_length=160)),
                ('description_cs', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('caption_cs', models.TextField(blank=True)),
                ('caption_en', models.TextField(blank=True)),
                ('sound_key', models.CharField(blank=True, max_length=80)),
                ('visual_key', models.CharField(max_length=80)),
                ('position_x', models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('position_y', models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('scale', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5.0)])),
                ('rotation', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('order', models.PositiveIntegerField(default=0)),
                ('highlight_priority', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exhibits', to='homeapp.category')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exhibits', to='homeapp.room')),
            ],
            options={
                'ordering': ['room__order', 'order', '-highlight_priority', 'name_en'],
                'indexes': [models.Index(fields=['room', 'order'], name='homeapp_exh_room_id_d61afe_idx'), models.Index(fields=['slug'], name='homeapp_exh_slug_1cffa1_idx'), models.Index(fields=['is_active'], name='homeapp_exh_is_acti_f3944b_idx')],
            },
        ),
    ]
