# Generated by Django 6.0.3 on 2026-03-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description_cs',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_en',
        ),
        migrations.AddField(
            model_name='exhibit',
            name='icon_name',
            field=models.CharField(blank=True, help_text='Název ikonky bez přípony, např. old-telephone', max_length=120),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='image_alt_cs',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='image_alt_en',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='image_name',
            field=models.CharField(blank=True, help_text='Název obrázku bez přípony, např. old-telephone', max_length=120),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='visual_key',
            field=models.CharField(help_text='Např. old-telephone', max_length=80),
        ),
        migrations.AddIndex(
            model_name='exhibit',
            index=models.Index(fields=['icon_name'], name='homeapp_exh_icon_na_625dec_idx'),
        ),
        migrations.AddIndex(
            model_name='exhibit',
            index=models.Index(fields=['image_name'], name='homeapp_exh_image_n_ba2cda_idx'),
        ),
    ]
