# Generated by Django 6.0.3 on 2026-03-13 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_remove_category_description_cs_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='exhibit',
            name='homeapp_exh_icon_na_625dec_idx',
        ),
        migrations.RemoveField(
            model_name='exhibit',
            name='icon_name',
        ),
    ]
